export const viewTask = [
  {
    id: 1,
    title: "Attend Nischal’s Birthday Party",
    Priority: "Moderate",
    status: "Not Started",
    date: "Created on: 20/06/2023",
    image: "/images/Rectangle 10.png",
    description: `
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    Buy gifts on the way and pick up cake from the bakery. (6 PM | Fresh Elements).....
    
    `,
  },
];
